name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        build: [debug, release]
    steps:
    - uses: actions/checkout@v3
    
    - name: make
      run: make CFG=${{matrix.build-type}}
